### ISSUE TITLE
Return error message as objects instead of string

### ISSUE THREAD

**Issue by wesleybl** [plone/plone.rest#176]
Errors are turned into a string when they are returned, as can be seen in:

https://github.com/plone/plone.rest/blob/8fdc78cd1420898d6ac954b5946f725ab63b33b3/src/plone/rest/errors.py#L60

However, validation errors are lists in `plone.restapi`:

https://github.com/plone/plone.restapi/blob/7e445b0d6ce5158dbea4f2e727a9aa84b7a2cc43/src/plone/restapi/deserializer/dxcontent.py#L52

When these errors reach Volto, we need to treat them as an array, but they are strings. We would have to use an `eval` to convert, which is not very recommended. See the discussion at:  https://github.com/plone/volto/issues/1868

It would be nice if the errors were already seen as a list in the return json. This may break some tests but I think it's the best solution.

**Comment by davisagli** [comment]
I consider it a bug that errors with a structure like this are flattened to a string rather than serialized as JSON. However, we need to make sure that if we change it, it ends up making things less broken rather than more broken in volto.

So, I think we should keep the current behavior in most cases, and implement a different serializer for specific cases like validation errors. Probably the code here should change to check if there is a JSON serialization adapter for the exception. If so, use it instead of str()

Then in plone.restapi we can add an adapter for ValidationError specifically. Of course, we also need to make sure volto is prepared to handle this structure on the client side.

**Comment by wesleybl** [comment]
@davisagli wouldn't just testing whether the exception is `ValidationError` solve it? Do we really need an adapter?

**Comment by davisagli** [comment]
@wesleybl That's a fair question. An adapter might be overkill here. On the other hand, it sounds like a useful feature to be able to override the serialization of any error using an adapter.

**Comment by davisagli** [comment]
@wesleybl I guess it's not straightforward to use an ISerializeToJson adapter here, since that interface is defined in plone.restapi. So yeah, go with a simple isinstance check for now.

**Comment by wesleybl** [comment]
It was possible to fix plone/volto#1868 without this change. See: https://github.com/plone/volto/pull/5808
