### ISSUE TITLE
ZCML files missing from release package

### ISSUE THREAD

**Issue by erral** [plone/plone.rest#34]
The version 1.0a2 package on pypi is missing the ZCML files,

**Comment by lukasgraf** [comment]
Thanks for the issue!

This is because of a [broken `MANIFEST.in`](https://github.com/plone/plone.rest/blob/master/MANIFEST.in) - package contents are below `/src`, not `/plone`.

@tisto the manifest itself is easy to fix for this specific issue (`s/src/plone/`). The question is, what files should ideally be included?

Currently these files are missing from the source dist:
```
  .landscape.yml
  base.cfg
  bootstrap-buildout.py
  bootstrap.py
  buildout.cfg
  heroku.cfg
  plone-4.3.x.cfg
  plone-5.0.x.cfg
  src/plone/rest/configure.zcml
  src/plone/rest/meta.zcml
  src/plone/rest/patches.zcml
  src/plone/rest/testing.zcml
  src/plone/rest/tests/file.pdf
  src/plone/rest/tests/image.png
  travis.cfg
  versions.cfg
```

Is there some canonical documentation somewhere on what should be included? If not, I'd probably lean towards "include everything" - things like `travis.cfg` don't make a lot of sense, but shouldn't hurt either.

Would we maybe want to include `bin/check-manifest` in the Travis CI checks? If we decide on *not* including everything, some ignores would need to be defined for that.

**Comment by tisto** [comment]
Fixed and released: https://pypi.python.org/pypi/plone.rest/1.0a3

check-manifest is included in code-analysis now.

Thanks @erral!
