### ISSUE TITLE
plone.restapi breaks Plone 5.0.4 File bulk uploads

### ISSUE THREAD

**Issue by tisto** [plone/plone.rest#50]
Moved here from https://github.com/plone/plone.restapi/issues/74

**Comment by bloodbare** [comment]
This issue is not fully solved, on calling @@fileUpload from the tinymce upload widget using POST and accept application/json.

Zope2 Traversal reaches the namespaceLookup function from zope.traversal which reaches a queryMultiAdapter with the RESTWrapper as contest, request and the name fileUpload (which does not exist as RESTWrapper is not Folderish). It never goes to publishTraverse because its a @@view and zope2 traversal goes to namespaceLookup in that case.

Plone 5.0.4
